Localization through lit-localize
Ocean-Industries-Concept-Lab/openbridge-webcomponents-legacy pull request #365
Opened 2024-10-24 12:33 UTC by hrobeers

For a project at [Mahi](https://mahi.be/) based on openbridge-webcomponents components we are in need for Spanish translations.
To support this we included localization through lit-localize and added some initial Spanish translations for the components that we are currently using.

Please review and let's discuss how to best support localization.
This implementation is currently serving our needs.

2024-11-02 18:11 UTC, tibnor requested changes
Hi!

Thanks for the contribution! I think it would be very nice to have the library internationalized :-D I must read up on lit-localize, before I can merge it in. Do I need to do anything in the build and distribution?

2024-11-02 18:11 UTC, tibnor commented on packages/openbridge-webcomponents/src/generated/locales/es-419.ts
I think this file should be added to .gitignore. As it is autogenerated

2024-11-04 08:46 UTC, hrobeers commented on packages/openbridge-webcomponents/src/generated/locales/es-419.ts
Yes agreed, will update the PR

2024-11-04 08:50 UTC, hrobeers commented
> Hi!
> 
> Thanks for the contribution! I think it would be very nice to have the library internationalized :-D I must read up on lit-localize, before I can merge it in. Do I need to do anything in the build and distribution?

I'm quite new to lit-localize as well, in a first stage it might be enough to just wrap all the to localize strings in `msg(string)`.
For our project this would be sufficient for now. I guess translations should come from final application and not from the library.

The idea of lit-localize is also that you can do all the wrapping of localized strings upfront and worry about the actual translations later.

Maybe we should keep it simple and just start wrapping strings?

2024-11-27 11:33 UTC, tibnor approved these changes

2024-11-27 11:38 UTC, merged